# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fe12098a00115dea485702d1d038e75b838ddb842d9d4f2e013be2c4afe09b30c910ec3eac95f180d9a74dbf79aa51bf60598947fc4367c14cee98a4e670a3e

test:
  secret_key_base: 30248285bf6c6792b79cc1af988b48242327724b3227427e6a30a83054073da09478932dd5de8ab42ae86e2e3e50bcfbfa11c82b900acfe837c2cd970948d301

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_token: <%= ENV["SECRET_TOKEN"] %>
